apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    owner: "Bilal Demir"
    description: "This is an example of annotation"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80