apiVersion: v1
kind: Pod
metadata:
  name: pod-init-container
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', "until nslookup myservice; do echo waiting for myservice; sleep 2; done"]
  containers:
  - name: app-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']