apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-namespace
  namespace: development
spec:
  containers:
  - name: container-namespace
    image: nginx
    ports:
    - containerPort: 80