apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-template
  labels:
    test: my-app-template
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80