apiVersion: v1
kind: Pod
metadata:
  name: imagesecrettest2
  labels:
    app: imagesecret
spec:
  containers:
  - name: imagesecretcontainer
    image: ozgurozturkregistry.azurecr.io/k8s:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regscrt